name: VALORANT
code: VAL
command_example: '1v4 3k jett vandal R4 -- mainline -- description'
aliases: [val, valorant]
fields:
  kill: {}
  clutch: {}
  agent:
    type: enum
    values: [Astra, Breach, Brimstone, Chamber, Clove, Cypher, Deadlock, Fade, Gekko, Harbor, Iso, Jett, Kayo, Killjoy, Miks, Neon, Omen, Phoenix, Raze, Reyna, Sage, Skye, Sova, Tejo, Viper, Veto, Vyse, Waylay, Yoru]
    aliases: {kj: Killjoy, ch: Chamber}
  map:
    type: enum
    values: [Abyss, Ascent, Bind, Breeze, Corrode, Fracture, Haven, Icebox, Lotus, Pearl, Split, Summit, Sunset]
  weapon:
    type: enum
    multiple: true
    values: [Classic, Shorty, Frenzy, Ghost, Bandit, Sheriff, Stinger, Spectre, Bucky, Judge, Bulldog, Guardian, Warden, Phantom, Vandal, Marshal, Outlaw, Operator, Ares, Odin, Headhunter, Tour de Force, Bladestorm, Showstopper, Overdrive]
    aliases: {hh: Headhunter, op: Operator, tdf: Tour de Force}
display_order: [clutch, kill, agent, map, weapon, mainline]
required_for_export: [agent, weapon]
