name: Apex Legends
code: APX
command_example: '1v3 3k wraith brokenmoon R4 -- mainline -- description'
aliases: [apx, apex, apexlegends]
fields:
  kill: {}
  clutch: {}
  legend:
    type: enum
    values: [Alter, Ash, Axle, Ballistic, Bangalore, Bloodhound, Catalyst, Caustic, Conduit, Crypto, Fuse, Gibraltar, Horizon, Lifeline, Loba, Mad Maggie, Mirage, Newcastle, Octane, Pathfinder, Rampart, Revenant, Seer, Sparrow, Valkyrie, Vantage, Wattson, Wraith]
  map:
    type: enum
    values: [Broken Moon, E-District, Kings Canyon, Olympus, Storm Point, World's Edge]
    aliases: {brokenmoon: Broken Moon, edistrict: E-District, kingscanyon: Kings Canyon, stormpoint: Storm Point, worldsedge: World's Edge}
display_order: [clutch, kill, legend, map, mainline]
suggested_fields: [legend, map]
