name: Apex Legends
code: APX
command_example: '1v3 3k wraith brokenmoon r301 R4 -- mainline -- description'
aliases: [apx, apex, apexlegends]
fields:
  kill: {}
  clutch: {}
  legend:
    type: enum
    values: [Alter, Ash, Axle, Ballistic, Bangalore, Bloodhound, Catalyst, Caustic, Conduit, Crypto, Fuse, Gibraltar, Horizon, Lifeline, Loba, Mad Maggie, Mirage, Newcastle, Octane, Pathfinder, Rampart, Revenant, Seer, Sparrow, Valkyrie, Vantage, Wattson, Wraith]
  map:
    type: enum
    values: [Broken Moon, E-District, Kings Canyon, Olympus, Storm Point, World's Edge]
    aliases: {brokenmoon: Broken Moon, edistrict: E-District, kingscanyon: Kings Canyon, stormpoint: Storm Point, worldsedge: World's Edge}
  weapon:
    type: enum
    multiple: true
    prefixes: [wpn]
    values: [HAVOC, Flatline, Hemlok, R-301, Nemesis, Alternator, Prowler, R-99, Volt, C.A.R., Devotion, L-STAR, Spitfire, Rampage, G7 Scout, Triple Take, 30-30 Repeater, Bocek, Charge Rifle, Longbow, Kraber, Sentinel, EVA-8, Mastiff, Mozambique, Peacekeeper, RE-45, P2020, Wingman, "Sniper's Mark"]
    aliases: {r301: R-301, r99: R-99, car: C.A.R., lstar: L-STAR, devo: Devotion, g7: G7 Scout, '3030': 30-30 Repeater, crifle: Charge Rifle, ev8: EVA-8, mozam: Mozambique, pk: Peacekeeper, re45: RE-45, smark: "Sniper's Mark"}
display_order: [clutch, kill, legend, map, weapon, mainline]
suggested_fields: [legend, map]
