name: Call of Duty Modern Warfare 4
code: MW4
command_example: '3k mult cachette m4 R4 -- mainline -- description'
aliases: [mw4, modernwarfare4, codmw4]
fields:
  kill: {}
  gamemode:
    type: enum
    prefixes: [mode]
    values: [Multiplayer, Killblock, Ground War, Warzone]
    aliases: {mult: Multiplayer, kblock: Killblock, gwar: Ground War, wz: Warzone}
  map:
    type: enum
    values: [Cachette, Lithium, Lotus, Rooftops, Silkworm, Transit 213, Kill Block, Imjin Farmlands, Wolves Stadium, Zodiac]
    aliases: {transit213: Transit 213, imjin: Imjin Farmlands, wolves: Wolves Stadium}
    links:
      Cachette: {gamemode: Multiplayer}
      Lithium: {gamemode: Multiplayer}
      Lotus: {gamemode: Multiplayer}
      Rooftops: {gamemode: Multiplayer}
      Silkworm: {gamemode: Multiplayer}
      Transit 213: {gamemode: Multiplayer}
      Kill Block: {gamemode: Killblock}
      Imjin Farmlands: {gamemode: Ground War}
      Wolves Stadium: {gamemode: Ground War}
      Zodiac: {gamemode: Warzone}
  weapon:
    type: enum
    multiple: true
    prefixes: [wpn]
    values: [Han86, M4, HyeonBurst, Kastov762, PatriotXMR, Axion, ISONightshade, PPSh-41, X-58Nyx, Wz.55Striga, Rezi12, FiNNLMG, Type73, MAR-9, Oris8.6, KG-7Vulcan, Signal.50, KraitP68, .50GS, Sang9mm, PILA, CombatKnife]
    aliases: {han: Han86, hyeon: HyeonBurst, kastov: Kastov762, patriot: PatriotXMR, iso: ISONightshade, ppsh: PPSh-41, nyx: X-58Nyx, striga: Wz.55Striga, rezi: Rezi12, finn: FiNNLMG, mar9: MAR-9, oris: Oris8.6, vulcan: KG-7Vulcan, signal: Signal.50, krait: KraitP68, gs: .50GS, sang: Sang9mm, knife: CombatKnife}
  killstreak:
    type: enum
    multiple: true
    prefixes: [ks]
    values: [Bomb Glider, Impact Warhead, Artillery Beacon, Crossfire, Combat Drone, Wheelson, Missile Salvo, Attack Helicopter, Tactical Nuke]
    aliases: {glider: Bomb Glider, warhead: Impact Warhead, artillery: Artillery Beacon, drone: Combat Drone, salvo: Missile Salvo, heli: Attack Helicopter, nuke: Tactical Nuke}
display_order: [kill, gamemode, map, weapon, killstreak, mainline]
suggested_fields: [gamemode, map, weapon]
